name: Build and Release

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Script
        run: |
          ./build.sh
          tar -czf oneclick.tar.gz -C dist .

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: oneclick.tar.gz
